---

- name: Add docker-engine repo and install docker
  shell: "curl -fsSL https://get.docker.com/ | sh"
  args:
    creates: /etc/yum.repos.d/docker-main.repo

- name: Start and Enable docker
  service:
    name: docker
    state: started
    enabled: true

- name: Add registry mirror to docker
  replace:
    # TODO: EnvironmentFile
    dest: /usr/lib/systemd/system/docker.service
    regexp: "ExecStart=/usr/bin/dockerd$"
    replace: "ExecStart=/usr/bin/dockerd {% if docker_registry_mirror_url %} --registry-mirror={{ docker_registry_mirror_url }} {% endif %} {% if docker_insecure_registry_url %} --insecure-registry={{ docker_insecure_registry_url }} {% endif %}"
  # notify: won't run at once
  register: daemon_reload

- name: Run systemd daemon-reload and restart docker
  systemd:
    daemon_reload: true
    name: docker
    state: restarted
  when: daemon_reload.changed

- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Install python-pip
  yum:
    name: python-pip
    state: present

- name: Install docker-py
  pip:
    name: docker-py
    version: 1.9.0