---

- name: Add docker-engine repo and install docker
  shell: "curl -fsSL https://get.docker.com/ | sh"
  args:
    creates: /etc/yum.repos.d/docker-main.repo

- name: Start and Enable docker
  service:
    name: docker
    state: started
    enabled: true

- name: Add registry mirror to docker
  replace:
    dest: /usr/lib/systemd/system/docker.service
    regexp: "ExecStart=/usr/bin/dockerd$"
    replace: "ExecStart=/usr/bin/dockerd --registry-mirror {{ docker_registry_mirror_url }} --insecure-registry {{ docker_insecure_registry_url }} "
  notify: Run systemd daemon-reload & Restart docker

- name: Install python-pip
  yum:
    name: python-pip
    state: present

- name: Install docker-py
  pip:
    name: docker-py
    version: 1.9.0