---
- name: [RedHat] Install epel-release
  yum:
    name: epel-release
    state: present
  when: '{{ ansible_os_family }} == "RedHat"'

- name: [RedHat] Install python-pip
  yum:
    name: python-pip
    state: present
  when: '{{ ansible_os_family }} == "RedHat"'

- name: [Debian] Install python-pip
  apt-get:
    name: python-pip
    state: present
  when: '{{ ansible_os_family }} == "Debian"'

- name: Install Pip extensions
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    extra_args: "{% if docker_pip_mirror_enable %} -i {{ docker_pip_mirror }} {% endif %}"
  with_items: "{{ docker_pip_packages }}"
