---
- name: Docker | RedHat | Install epel-release
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: Docker | RedHat | Install python-pip
  yum:
    name: python-pip
    state: present
  when: ansible_os_family == "RedHat"

- name: Docker | Debian | Install python-pip
  apt:
    name: python-pip
    state: present
  when: ansible_os_family == "Debian"

- name: Docker | Install Pip extensions
  pip:
    name: "{{ item.name }}"
    # version: "{{ item.version }}"
    extra_args: "{% if docker_pip_mirror_enable %} -i {{ docker_pip_mirror }} {% endif %}"
  with_items: "{{ docker_pip_packages }}"
